// AUTO-GENERATED by scripts/generate-logo-sdf.mjs. Do not edit by hand.
export const LOGO_SDF_WIDTH = 1024 as const;
export const LOGO_SDF_HEIGHT = 1057 as const;
export const LOGO_SDF_SPREAD = 20 as const;
