// Reproducible logo pipeline:
//   node scripts/trace-logo.mjs
// Traces public/calaltonlogo.png (white-on-black wordmark) into a tight SVG path
// and writes the React-consumable module at
// src/components/brand/CalAltonMark/logo-path.ts. Re-run whenever the source
// PNG changes.
import { writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import potrace from "potrace";
import sharp from "sharp";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const input = resolve(root, "public/calaltonlogo.png");
const cacheDir = resolve(root, ".cache");
const previewSvg = resolve(cacheDir, "calaltonlogo.traced.svg");
const moduleOut = resolve(
  root,
  "src/components/brand/CalAltonMark/logo-path.ts",
);

// Supersample the source 4× with a light blur before tracing, so potrace has a
// dense, smooth bitmap to fit curves to (kills the pixel-step "ridges").
const upscaled = await sharp(input)
  .resize({ width: 1448 * 4, kernel: sharp.kernel.lanczos3 })
  .blur(1.4)
  .toBuffer();

const params = {
  blackOnWhite: false, // letters are light on a dark field
  threshold: 128,
  turdSize: 400, // drop tiny specks (scaled up 4×)
  alphaMax: 1.3334, // maximum corner smoothing → rounded curves
  optCurve: true,
  optTolerance: 0.8, // aggressive curve fitting → fewer, smoother segments
  color: "#ffffff",
  background: "transparent",
};

const svg = await new Promise((res, rej) => {
  potrace.trace(upscaled, params, (err, out) => (err ? rej(err) : res(out)));
});

const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1] ?? "";
const paths = [...svg.matchAll(/ d="([^"]+)"/g)].map((m) =>
  m[1].replace(/\s+/g, " ").trim(),
);
if (!viewBox || paths.length === 0) throw new Error("trace produced no paths");

const ts = `// AUTO-GENERATED by scripts/trace-logo.mjs from public/calaltonlogo.png.
// Do not edit by hand — re-run the trace script to regenerate.
export const CAL_ALTON_VIEWBOX = ${JSON.stringify(viewBox)} as const;
export const CAL_ALTON_PATH =
  ${JSON.stringify(paths[0])};
`;

await mkdir(cacheDir, { recursive: true });
await writeFile(previewSvg, svg, "utf8");
await writeFile(moduleOut, ts, "utf8");

console.log(`traced ${viewBox} (${paths[0].length} chars) -> ${moduleOut}`);
